version: "3.5"

services: 
  bot:
    build: .
    restart: unless-stopped
    links:
      - postgres
    depends_on: 
      - postgres
      - lavalink
    environment:
      TOKEN: ${TOKEN}
      OWNER_ID: ${OWNER_ID}
      PREFIX: ${PREFIX}
      DB_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_USER}"
    
  postgres:
    image: postgres:13
    restart: unless-stopped
    hostname: postgres
    volumes: 
      - /postgres_data:/var/lib/postgresql
    environment: 
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432

  lavalink:
    image: fredboat/lavalink:master
    restart: unless-stopped
    hostname: lavalink
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - 2333:2333

volumes:
  postgres_data:
    